spring:
  application:
    name: Spring-Boot-Learning
  #  profiles:
  #    active: prod
  # 自定义配置mvc静态资源路径
  mvc:
    static-path-pattern: /static/, /public/
  # 数据源配置
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306:testdb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  # freemarker 视图解析配置
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
    charset: utf-8
  # thymeleaf 试图解析配置
  thymeleaf:
    prefix: classpath:/html/
    cache: false
  # 开启缓存
  cache:
    ehcache:
      config: classpath:ehcache.xml
  # 配置热部署
  devtools:
    restart:
      # 设置重启目录
      additional-paths: src/main/java
      # 解决项目重新编译后接口报404的问题
      poll-interval: 3000
      quiet-period: 1000
server:
  port: 8080
# 日志配置
logging:
  pattern:
    console: "%d{yyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n"
  file:
    name: "springboot.log"
    path: "."
# MyBatis配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.tornado4651.springboot.dao
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  auto-dialect: mysql
